export const tradingPsychologyQuotes: string[] = [
  "Discipline is the bridge between goals and trading success.",
  "Fear and greed are your biggest opponents in the market.",
  "Trade what you see, not what you feel.",
  "Your mindset determines your trading outcomes.",
  "Risk only what you can afford to lose.",
  "Losses are lessons, not failures.",
  "Did you know? Journaling your trades improves long-term performance.",
  "Good traders focus on process, not profit.",
  "Never let one trade define your identity.",
  "Emotions are signals—learn to listen without reacting.",
  "Did you know? Most successful traders have losing trades every week.",
  "Patience separates gamblers from professionals.",
  "Chasing losses leads to bigger losses.",
  "Did you know? Consistent position sizing reduces stress and errors.",
  "A clear mind sees better setups.",
  "Good practice: Walk away after hitting your daily loss limit.",
  "Confidence comes from preparation, not prediction.",
  "Success in trading = Strategy + Psychology + Risk Management.",
  "Did you know? Overtrading is the #1 reason retail traders fail.",
  "Every trade must have a reason—hope isn’t one.",
  "Sleep well. Trade better.",
  "Good practice: Review your journal weekly, not just monthly.",
  "Control your mind or the market will control it for you.",
  "Did you know? Trading in a bad mood increases impulsive decisions.",
  "There’s no perfect system, only consistent execution.",
  "Discipline is doing what you planned even when you don’t feel like it.",
  "A single loss doesn’t end your career—giving up does.",
  "Risk management is self-respect in action.",
  "Take breaks. Your brain trades too.",
  "Did you know? Traders with a pre-trading routine perform 25% better on average.",
  "The best traders are masters of their own emotions.",
  "You can’t control the market, but you can control your reaction to it.",
  "Fear and greed destroy more accounts than bad analysis ever could.",
  "You win by staying in the game, not by chasing the game.",
  "Every trade is a test of your patience, not just your strategy.",
  "You are not your P&L. You are your discipline.",
  "Great traders don’t predict. They prepare and react.",
  "Emotional control is the real alpha.",
  "The market is neutral. Your interpretation is not.",
  "If you’re desperate to make money, you’ll lose it.",
  "Detachment is power. Treat every trade like just another trade.",
  "You don’t need to win every day. You need to trade smart every day.",
  "Let go of the need to be right. Embrace the need to be consistent.",
  "Traders fail not because of the market—but because of the mirror.",
  "Stay humble. The market punishes arrogance.",
  "How you handle losses defines your career.",
  "The best setups are the ones you can walk away from if they don’t align.",
  "Your mindset is either your weapon or your weakness.",
  "Don’t trade to feel something. Trade to do something.",
  "Patience is not passive. It’s the skill of waiting for the right moment.",
  "Be mentally flatlined—never too high, never too low.",
  "Forgive yourself fast. But learn even faster.",
  "The market isn’t your enemy. Your impatience might be.",
  "Focus on perfect execution, not perfect results.",
  "Confidence without discipline is dangerous. Build both.",
  "Protecting capital is priority one. Always.",
  "If your stop loss feels too tight, your position size is too big.",
  "Capital preserved is opportunity preserved.",
  "Proper risk management will keep you alive while your edge develops.",
  "Trade small enough that losing doesn’t hurt—but big enough that winning matters.",
  "Limit losses. Let profits compound.",
  "A good trader makes money. A great trader protects money.",
  "Every blown account had bad risk rules once.",
  "Ask yourself before each trade: What’s the worst-case scenario?",
  "Consistency in risk leads to consistency in results.",
  "If one trade can wipe you out, your system is broken.",
  "Never increase size to recover a loss. That’s gambling, not trading.",
  "Risk management isn’t optional—it’s your lifeline.",
  "Avoid revenge trading. Walk away, regroup, come back.",
  "A proper plan should include where to exit when you\'re wrong.",
  "If you don’t have a stop loss, you have a problem.",
  "Successful traders think in probabilities—not certainties.",
  "Every trade should have a purpose, not just potential.",
  "Let the trade come to you. Don’t chase it with leverage.",
  "If you treat trading like a business, it will pay like one.",
  "Record everything. Track progress. Improve constantly.",
  "The best traders have boring routines but exciting results.",
  "Plan your trade. Trade your plan. Review your plan.",
  "Daily reflection builds weekly growth.",
  "Avoid trading when tired, emotional, or distracted.",
  "A trading journal is your mirror and your mentor.",
  "One missed rule often leads to many missed opportunities.",
  "Always enter a trade with a clear exit plan.",
  "Your morning routine affects your market performance.",
  "Don\'t start the day chasing yesterday’s losses.",
  "Start each day with clarity, not urgency.",
  "Use technology to support discipline, not avoid it.",
  "Routines create consistency. Consistency creates success.",
  "One hour of weekly review can save you weeks of mistakes.",
  "Every trade should follow a rule—not a feeling.",
  "Markets are dynamic. So should be your ability to adapt.",
  "Don’t trade based on noise. Wait for your signal.",
  "No setup? No trade. That’s still a decision.",
  "Let others chase the hype. You stay grounded in logic.",
  "A clear head will outperform a clever chart.",
  "Volume confirms. Emotions distort.",
  "Build your strategy like an engineer. Test like a scientist.",
  "Not trading is a position too. Cash is a position.",
  "Focus on mastering one setup. That’s all you need to win.",
  "Trade less, think more. Results follow clarity.",
  "Embrace boredom. Consistent profits often feel dull.",
  "Trade what you see. Not what you hope.",
  "Have rules for every scenario—including when to stop.",
  "Use loss as feedback, not failure.",
  "Every trade teaches you something—if you listen.",
  "Did you know? Most successful traders risk less than 1% per trade.",
  "Did you know? Journaling can increase performance by over 20% in some traders.",
  "Did you know? Missing sleep affects trading performance like a 0.05 blood alcohol level.",
  "Did you know? Traders with daily review habits improve 2x faster than those who don’t.",
  "Did you know? Overtrading is the #1 mistake traders admit to after losses.",
  "Did you know? Trading without a plan is more stressful than flying without a map.",
  "Did you know? Confidence in trading grows faster from discipline than from wins.",
  "Did you know? Market noise increases stress and reduces clarity by up to 30%.",
  "Did you know? Traders who meditate or journal experience lower emotional drawdown.",
  "Did you know? Losses feel 2.5x more powerful than gains psychologically.",
  "Did you know? 80% of traders quit due to mindset—not market conditions.",
  "Did you know? Reward-to-risk ratio is more important than win rate.",
  "Did you know? Checking your P&L too often increases impulsive behavior.",
  "Did you know? Simpler strategies tend to outperform overcomplicated ones long term.",
  "Did you know? Consistency beats intensity in trading habits.",
  "Did you know? Most market moves are noise. Your edge is in waiting.",
  "Did you know? Journaling losses helps reduce future emotional reactivity.",
  "Did you know? Traders with routine logins and breaks have longer profitable careers.",
  "Did you know? The average funded trader failed at least 3 times before succeeding.",
  "Did you know? Peak performance happens in a relaxed state—not under pressure.",
];

export function getDailyQuote(): string {
  const today = new Date();
  const dayOfYear = Math.floor((today.getTime() - new Date(today.getFullYear(), 0, 0).getTime()) / 1000 / 60 / 60 / 24);
  const quoteIndex = dayOfYear % tradingPsychologyQuotes.length;
  return tradingPsychologyQuotes[quoteIndex];
}
